SHELL := /bin/bash

Kollek_Alameddine_Pernklau.zip:
	#rm Kollek_Alameddine_Pernklau.zip
	ls -I "*.md" -I "*.zip" -I makefile -I "*.tex" | xargs zip -r Kollek_Alameddine_Pernklau.zip

	#ls -I "*.md" -I "*.zip" -I makefile -I "*.tex" | xargs tar --hard-dereference -cvhf Kollek_Alameddine_Pernklau.zip
