import numpy as np
from libc.stdlib cimport malloc, free

def lin_con(int a, int b, int m, int lenght,int initial_value=0):
    """Return numpy array of lenght filled with 'random' numbers generated by a linear congruential generator."""
    cdef int *return_value = <int *> malloc(sizeof(int)*lenght)

    return_value[0] = initial_value
    for x in range(1, lenght):
        return_value[x] = (a * return_value[x - 1] + b) % m

    ret = np.array([return_value[i] for i in range(lenght)]) / m
    free(return_value)
    return ret

