import pandas as pd
import numpy as np
import ROOT


def lin_con(a, b, m, lenght, initial_value=0):
    """Return numpy array of lenght filled with 'random' numbers generated by a linear congruential generator."""
    return_value = np.zeros(lenght)

    assert initial_value <= m
    return_value[0] = initial_value
    for x in range(1, lenght):
        return_value[x] = (a * return_value[x - 1] + b) % m

    return np.array(return_value) / m


# Generate random numbers for later use
samples = 10000


data_a = pd.DataFrame()
for i in range(0, 10000, 2786):
    data_a["Anfangswert " + str(i)] = lin_con(1601, 3456, 10000, samples, initial_value=i)

data_b = pd.DataFrame()
for i in range(0, 10000, 2786):
    root_rnd = ROOT.TRandom(i)
    data_b["Anfangswert " + str(i)] = [root_rnd.Rndm() for i in range(samples)]

data_c = pd.DataFrame()
for i in range(0, 10000, 237):
    data_c["Anfangswert " + str(i)] = lin_con(1601, 3456, 10000, samples, initial_value=i)

data_a.to_csv("data/lin_con.csv")
data_b.to_csv("data/trandom.csv")
data_c.to_csv("data/lin_con_big.csv")
