import numpy as np
import pandas as pd


def lin_con(a, b, m, lenght, initial_value=0):
    """Return numpy array of lenght filled with 'random' numbers generated by a linear congruential generator."""
    return_value = np.zeros(lenght)

    return_value[0] = initial_value
    for x in range(1, lenght):
        return_value[x] = (a * return_value[x - 1] + b) % m

    return pd.DataFrame(return_value / m, columns=['Random Numbers'])
