import numpy as np


def lin_con(int a, int b, int m, int lenght,int initial_value=0):
    """Return numpy array of lenght filled with 'random' numbers generated by a linear congruential generator."""
    cdef int return_value[lenght]

    return_value[0] = initial_value
    for x in range(1, lenght):
        return_value[x] = (a * return_value[x - 1] + b) % m

    return np.array(return_value) / m

# a)
test_array = lin_con(1601, 3456, 10000, 100000000)
